server:
  port: 8980

eureka:
  instance:
    hostname: configserver
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/sreeseelam/config-server
          force-pull: true
